name: check Az Cli and Docker installation

on:
  workflow_dispatch:

jobs:
  check-versions:
    runs-on: ubuntu-latest

    steps:
    - name: Check Az CLI version
      run: az --version
  
    - name: Check Docker version
      run: docker --version
