name: Check main branch

on:
    push:
        branches:
            - main
jobs:
    automate-pipeline:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout source repository
          uses: actions/checkout@v2

        - name: Check if the specific file is modified
          id: check_file
          run: |
            if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^folder' ; then
                echo "::set-output name=changed::true"
            else
                echo "::set-output name=changed::false"
            fi
        - name: Check the value of the output is true
          if: steps.check_file.outputs.changed == 'true'
          run: |
            echo the value is true
        - name: Check the value of the output is false
          if: steps.check_file.outputs.changed == 'false'
          run: |
            echo the value is false


        

        