name: upload artifact

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Set up JDK
      run: echo "end of the code so far"
    - name: create a new folder
      run: mkdir newfolder && echo "first.html" >> ./newfolder/first.html && ls -a ./newfolder/ && cat ./newfolder/first.html
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: greeting-jar
        path: ./newfolder

  download:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: download the artifact
      uses: actions/download-artifacts@v2
      with:
        name: greeting-jar
    - shell: bash
      run: |
        ls -a
