name: to-json-test

on:
  workflow_dispatch:

jobs:
  print_to_log:
    runs-on: ubuntu-latest

    steps:
      - name: Dump Github context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
