name: my starter workflow


on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - name: RUn a multi-line script

        run: |
          echo Add other actions to build,
          echo test, and deploy your project

  call-workflow-in-local-repo:
    strategy:
      matrix:
        nodeversion: [14, 16, 18, 20]
    uses: ./.github/workflows/chap08_matrix_reusableWorkflow.yml
    with:
      #node: 8
      node: ${{ matrix.nodeversion }}
      
  
