## for concurrency of pull requests, it waits if the previous PRs are finished, then trying to run the next PR

# for more watch this playlist on youtube: https://www.youtube.com/watch?v=PZ_A0QiLvz8&list=PLiO7XHcmTsleGRnjT2o0ILzXUkzFJ87eR&index=2
name: Concurrency PR


on:
  pull_request:
    branches: [ main ]

concurrency:

  group: build-and-test

jobs:
  build-and-test-on-pr:
    name: Build and Test on Pull Request
    runs-on: ubuntu-latest

    steps:

    - name: Build the Code
      run: |
        echo "starting code build!"
        sleep 30s
        echo "finish code build"

    - name: test the code
      run: |
        echo "starting code build"
        sleep 30s
        echo "finish the code" 
